### ISSUE TITLE
Bug en el nombre

### ISSUE THREAD

**Issue by froyd42** [BaldricNetwork/Issues#2]
https://gyazo.com/2e9b3a3cf65a659d1495188da35b3954

Esto pasa en el foro.
Recargué la página varias veces para revisar si era un bug o un problema mio, pero al parecer es un bug.

**Comment by froyd42** [comment]
Al parecer fue un bug por un momento, ahora recargué la página y volvió a la normalidad.

**Comment by GetSomeBlocks** [comment]
Listo
