### ISSUE TITLE
Cannot make topics on the site

### ISSUE THREAD

**Issue by Palmidence** [BaldricNetwork/Issues#4]
I'm trying to release more maps, but I keep getting an error "tu tema fue creado con exito".

**Comment by RubeVi** [comment]
Its because your token time expire, if you took more than 10 minutes to create the post it expire your token and is unable to create the topic, by the way it show a successful message. We are going to check it!

**Comment by RubeVi** [comment]
Fixed, we improve the mysql query to avoid errors
