### ISSUE TITLE
[BUG] Normal players has the staff trophy.

### ISSUE THREAD

**Issue by McFanta** [BaldricNetwork/Issues#8]
Hello there Baldric developers, I'm here to imform you guys that users has the staff trophy. For example my <a href="https://baldricnetwork.com/u/mcfanta_">profile</a>. Only staff members such as moderators, map developers and etc should have that trophy. Please fix that bug. Regards <a href="https://github.com/mcfanta">McFanta_</a>

**Comment by RubeVi** [comment]
Thanks for reporting it! now temporarily fixed. Check out in our revisions page
http://baldricnetwork.com/revisiones
